spring.application.name=hotel-booking
spring.datasource.url=jdbc:mysql://localhost:3306/hotel_booking_db
spring.datasource.username=yourusernamehere
spring.datasource.password=yourpasshere

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true